name: ci

# Controls when the action will run. Triggers the workflow on push for any branch, and
# pull requests to master
on:
  push:
    branches: [ master ]
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest

    # run the job on every combination of "os" above
    runs-on: ${{ matrix.os }}

    steps:
    # tell git not to convert line endings
    - name: Install Windows dependencies
      if: matrix.os == 'windows-latest'
      run: |
        git config --global core.autocrlf false

    - name: Install Ubuntu dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install libzmq3-dev sbcl

    - name: Install MacOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install clozure-cl czmq sbcl

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Jupyter
      run: |
        pip install --upgrade pip setuptools wheel jupyter jupyter_kernel_test
        jupyter --version

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Quicklisp and setup source registry
      run: |
        curl -kLO https://beta.quicklisp.org/quicklisp.lisp
        mkdir -p $HOME/.config/common-lisp
        echo "(:source-registry (:tree (\"$PWD\")) :inherit-configuration)" >$HOME/.config/common-lisp/source-registry.conf

    - name: Clone shasht (only need when Quicklisp is out of date)
      run: |
        git clone https://github.com/yitzchak/shasht.git ~/quicklisp/local-projects/shasht

    - name: Install SBCL kernel
      run: |
        sbcl --non-interactive --load scripts/usr-install.lisp sbcl

    - name: Install CCL kernel
      if: matrix.os == 'macos-latest'
      run: |
        ccl64 --batch --load scripts/usr-install.lisp

    # - name: Install ECL Jupyter kernel
    #   if: matrix.os == 'ubuntu-latest'
    #   run: |
    #     ecl -shell scripts/usr-install.lisp

    - name: Run kernel tests
      run: |
        python tests/client.py
